# Lecture 2: Tensor

In [1]:
import torch
import numpy as np

## Quick Notes for Tensors:
* A torch. Tensor is a multidimensional matrix containing elements of a single data type.
* Similar to NumPy Arrays, but full of fun things that make them work better on GPU's (vs regula CPU's)
* Default data type of float 32.
* More suitable for deep learning than a numpy array.

## Section 1: Quick Recap and Introduce to PyTorch Tensor

1. Python List:

In [2]:
a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

2. NumPy Arrays:

In [3]:
x = np.random.rand(2, 3, 4)
x

array([[[0.89280331, 0.91171353, 0.09940462, 0.9061497 ],
        [0.83186229, 0.9992721 , 0.89291557, 0.65289589],
        [0.62612792, 0.00127658, 0.66429875, 0.75324296]],

       [[0.82686983, 0.94999017, 0.08475549, 0.67242711],
        [0.60851473, 0.86878726, 0.36619619, 0.55649911],
        [0.7304278 , 0.55616967, 0.82578149, 0.78970875]]])

3. Tensor:

In [4]:
y = torch.rand(2, 3, 4)
y

tensor([[[0.9802, 0.4791, 0.4770, 0.2094],
         [0.2527, 0.0408, 0.6955, 0.7802],
         [0.7278, 0.2509, 0.0303, 0.3329]],

        [[0.5446, 0.9159, 0.5291, 0.2458],
         [0.8823, 0.1775, 0.6771, 0.5316],
         [0.5628, 0.5639, 0.7252, 0.7193]]])

4. Convert NumPy arrays to tensors:

In [5]:
z = torch.tensor(x)
z

tensor([[[0.8928, 0.9117, 0.0994, 0.9061],
         [0.8319, 0.9993, 0.8929, 0.6529],
         [0.6261, 0.0013, 0.6643, 0.7532]],

        [[0.8269, 0.9500, 0.0848, 0.6724],
         [0.6085, 0.8688, 0.3662, 0.5565],
         [0.7304, 0.5562, 0.8258, 0.7897]]], dtype=torch.float64)

# Lecture 3: Tensor Operations

## Section 1: Reshape and View
**In summary differences between shape and view:**
1. Use .view() when you are certain the tensor is contiguous, and you desire memory sharing (i.e., you want changes to reflect in both the original and reshaped tensor).
2. Use .reshape() when you need to change the shape regardless of contiguity and are less concerned about strict memory sharing, as it might create a copy. If you are unsure about the contiguity of your tensor, reshape() is generally the safer choice as it will not raise an error.

In [6]:
my_torch1 = torch.arange(10)

my_torch1, my_torch1.reshape([2, 5]), my_torch1.view([2, 5])

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]))

## Section 2: Reshape if we don't know the number of items using -1

In [7]:
my_torch2 = torch.arange(15)

my_torch2.reshape([3, -1]), my_torch2.reshape([-1, 3])

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]))

## Section 3: With reshape and view, relative tensors will update if original tensors make changes.
**_Also apply to NumPy, Pandas_**

In [8]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.reshape([2, 5])

my_torch3, my_torch4

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]))

In [9]:
my_torch3[1] = 123

my_torch3, my_torch4

(tensor([  0, 123,   2,   3,   4,   5,   6,   7,   8,   9]),
 tensor([[  0, 123,   2,   3,   4],
         [  5,   6,   7,   8,   9]]))

## Section 4: Slices
1. Grab a Specific Item:

In [10]:
my_torch5 = torch.arange(15)
my_torch5[7]

tensor(7)

2. Grab Slice:
    * Return in a row, cause [:, 1] mean pick all row and pick column idx=1 item
    * Return in a column, cause [:, 1:2] mean pick all row and pick column form idx=1 to idx=1, number after colon will not be included.

In [11]:
my_torch6 = my_torch5.reshape([5, 3])
my_torch6[:, 1], my_torch6[:, 1:2]

(tensor([ 1,  4,  7, 10, 13]),
 tensor([[ 1],
         [ 4],
         [ 7],
         [10],
         [13]]))

# Lecture 4: Tensor Math Operations

**Tensor Math Operations:**
* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shorthand, Longhand
* Reassignment

In [12]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])

## Section 1: Addition

In [13]:
a + b, torch.add(a, b), a.add(b)

(tensor([ 6,  8, 10, 12]), tensor([ 6,  8, 10, 12]), tensor([ 6,  8, 10, 12]))

## Section 2: Subtraction

In [14]:
a - b, torch.subtract(a, b)

(tensor([-4, -4, -4, -4]), tensor([-4, -4, -4, -4]))

## Section 3: Multiplication

In [15]:
a * b, torch.multiply(a, b)

(tensor([ 5, 12, 21, 32]), tensor([ 5, 12, 21, 32]))

## Section 4: Division

In [16]:
a / b, torch.div(a, b)

(tensor([0.2000, 0.3333, 0.4286, 0.5000]),
 tensor([0.2000, 0.3333, 0.4286, 0.5000]))

## Section 5: Remainders Module

In [17]:
b % a, torch.remainder(b, a)

(tensor([0, 0, 1, 0]), tensor([0, 0, 1, 0]))

## Section 6: Exponents / Power

In [18]:
a ** b, torch.pow(a, b)

(tensor([    1,    64,  2187, 65536]), tensor([    1,    64,  2187, 65536]))

## Section 7: Reassignment with underscore

**Recommended:**

In [19]:
a = a + b
a

tensor([ 6,  8, 10, 12])

In [20]:
a += b
a

tensor([11, 14, 17, 20])

**Not Recommended:**

In [21]:
a = a.add_(b)
a

tensor([16, 20, 24, 28])